--SET search_path TO s501787;

INSERT INTO form_of_education VALUES
(1, 'DISTANCE_EDUCATION'),
(2, 'FULL_TIME_EDUCATION'),
(3, 'EVENING_CLASSES')
ON CONFLICT (id) DO NOTHING;

INSERT INTO semester VALUES
(1, 'FIRST'),
(2, 'SECOND'),
(3, 'THIRD'),
(4, 'FIFTH'),
(5, 'EIGHTH')
ON CONFLICT (id) DO NOTHING;

INSERT INTO country VALUES
(1, 'RUSSIA'),
(2, 'USA'),
(3, 'THAILAND'),
(4, 'SOUTH_KOREA')
ON CONFLICT (id) DO NOTHING;